// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $contacto from "./routes/contacto.tsx";
import * as $contactos from "./routes/contactos.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $pantallaDNI from "./routes/pantallaDNI.tsx";
import * as $algo from "./islands/algo.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/contacto.tsx": $contacto,
    "./routes/contactos.tsx": $contactos,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/pantallaDNI.tsx": $pantallaDNI,
  },
  islands: {
    "./islands/algo.tsx": $algo,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
